// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGvxchA57Fxy9a-OzLULyVt5TuG1vZNxw',
    appId: '1:391737147539:web:5017b96e5a725721e2cd66',
    messagingSenderId: '391737147539',
    projectId: 'login-try-d330f',
    authDomain: 'login-try-d330f.firebaseapp.com',
    storageBucket: 'login-try-d330f.firebasestorage.app',
    measurementId: 'G-K613T9WSET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxVsubwrhxPEPRI0XKAYbxQlWI8WPt1lM',
    appId: '1:391737147539:android:7641541083ba8c30e2cd66',
    messagingSenderId: '391737147539',
    projectId: 'login-try-d330f',
    storageBucket: 'login-try-d330f.firebasestorage.app',
  );

}